version: "3.0"
services:
  nats-server:
    image: nats:2.9.14-alpine
    ports:
      - "4222:4222"

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ante-finance-interview
      - TZ=GMT+3
      - PGTZ=GMT+3
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data:
